# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-02-21 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190221_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_project_setting',
            name='host',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='api_test_case_step',
            name='host',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='api_test_report_for_case_step',
            name='host',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='database_setting',
            name='db_host',
            field=models.CharField(max_length=200),
        ),
    ]
