# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-02-21 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190221_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='function_setting',
            name='project_type',
            field=models.CharField(default='UI项目', max_length=10),
            preserve_default=False,
        ),
    ]
