# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-19 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_function_setting_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database_setting',
            name='project_id',
            field=models.CharField(max_length=300),
        ),
    ]
