# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-22 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20190322_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_project_setting',
            name='environment_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database_setting',
            name='environment_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ui_project_setting',
            name='environment_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
