# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-22 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20190322_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='global_variable_setting',
            name='env_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
