# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-25 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20190322_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global_variable_setting',
            name='project_id',
            field=models.CharField(max_length=500),
        ),
    ]
