# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-26 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20190325_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='ui_test_plan',
            name='browsers_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
